#!bin/bash

echo "Please enter the MAC address of your ground station laptop"
read mac

echo "Please enter the IP address of your ground station laptop"
read ip

if [[ "$mac" = "" ]]
then
	mac="ENTER GS LT MAC ADDRESS HERE"
fi

if [[ "$ip" = "" ]]
then
	ip="ENTER GS LT IP ADDRESS HERE"
fi

#Install modified libcamera

sudo systemctl enable ssh #Enable SSH
sudo systemctl start ssh

sudo systemctl stop cups.service cups-browsed.service bluetooth.service hciuart.service #Turn off unnecessary services
sudo systemctl disable cups.service cups-browsed.service bluetooth.service hciuart.service
sudo systemctl mask bluetooth.service hciuart.service

sudo apt purge avahi-daemon pipewire pipwire-bin modemmanager packagekit libnss-mdns #Delete unnecessary processes

sudo apt install vim vim-runtime vim-common #Install Vim because we can

sudo apt install tcpdump #So I can take a network dump

sudo arp -S $ip $mac #Set ARP mac address for ground laptop

command5_output=$(git clone https://github.com/25nlambert/BOREALIS_Cam.git)
echo "$command5_output"

sudo cp BOREALIS_Cam/config.txt /boot/config.txt #Replace config file with camera one

sudo cp BOREALIS_Cam/dhcpcd.conf /etc/dhcpcd.conf #Replace dhcp file with working one for static IP

sudo cp BOREALIS_Cam/.bashrc /home/pi/.bashrc #Replace shell config

sudo cp BOREALIS_Cam/BOREALIS_CAM.service /etc/systemd/system #Copy service file

sudo chmod +x /home/pi/BOREALIS_Cam/start_stream
sudo chmod +x /home/pi/BOREALIS_Cam/edit_stream

sudo systemctl enable BOREALIS_CAM.service

sudo reboot
