#!bin/bash

ip="192.168.1.23"

while getopts ":ip:d:" option; do
  case $option in
    ip)
      ip="$OPTARG"
      ;;
    reinstall)
      reinstall=1
      ;;
    *)
      echo "Usage: $0 [-f ip - Will set the static ip] [-reinstall - Will redownload lib-camera]"
      exit 1
      ;;
  esac
done

if [ ! -f "install_pivariety_pkgs.sh" ] || [ "$reinstall" -eq 1]; then

    command1_output=$(wget -O install_pivariety_pkgs.sh https://github.com/ArduCAM/Arducam-Pivariety-V4L2-Driver/releases/download/install_script/install_pivariety_pkgs.sh)
    echo "$command1_output"

    sudo chmod +x install_pivariety_pkgs.sh

    command3_output=$(./install_pivariety_pkgs.sh -p libcamera_dev)
    echo "$command3_output"

    command4_output=$(./install_pivariety_pkgs.sh -p libcamera_apps)
    echo "$command4_output"

fi

command5_output=$(git clone --force https://github.com/25nlambert/BOREALIS_Cam.git)
echo "$command5_output"

line_number=$(grep -n "camera_auto_detext" "/boot/config.txt" | cut -d ':' -f1)
echo "camera_auto_detect line found"

sudo sed -i '0,/camera_auto_detect=1/s/camera_auto_detect=1.*/camera_auto_detect=0'"\n"'dtoverlay=imx477/' /boot/config.txt
echo "Turned off camera auto detection"
echo "Added IMX477 Config"

sudo sed -i '0,/#interface eth0/s/#interface eth0.*/interface eth0/' /etc/dhcpcd.conf
echo "Enabled interface eth0"

sudo sed -i "0,/#static ip_address/s/#static ip_address.*/static ip_address=$ip/" /etc/dhcpcd.conf
echo "Enabled and set static ip_address to $ip"

command7_output=$(sudo cp BOREALIS_Cam/BOREALIS_CAM.service /etc/systemd/system)
echo "$command7_output"

sudo chmod +x BOREALIS_Cam/start_stream

sudo systemctl enable BOREALIS_CAM.service

sudo reboot
