#!/bin/bash

sleep 60

source /home/$USER/BOREALIS_Cam/config.conf #Pull in config values from file

sudo /usr/sbin/arp -s $ip $mac #Set ARP mac address for ground laptop

/usr/bin/rpicam-vid --camera 1 --width $WIDTH --height $HEIGHT -g 15 -b $BITRATE --vflip -t 0 --framerate $FRAMERATE -n | /usr/bin/ffmpeg -r $FRAMERATE -f h264 -i - -an -vcodec copy -r $FRAMERATE -f rtp_mpegts rtp://$GSip:8555?localaddr=$ip\&ttl=2 -vcodec copy -f mpegts /home/$USER/Desktop/`date '+%Y%m%d-%H%m%S.%N'`.mpegts
