#!bin/bash

source /home/$USER/BOREALIS_Cam/config.conf #Pull in config values from file

echo "Please enter the setting you want to change, or 'help' for a list of changable settings"
read input
while [ "$input" = "help" ]
do
	echo "Changable settings are as follows:"
	echo "Bitrate, bitrate, b"
	echo "Framerate, framerate, f"
	echo "Height, height, h"
	echo "Width, width, w"
	echo ""
	echo "Please enter the setting you want to change, or 'help' for a list of changable settings"
	read input
done

if [[ "$input" = "Bitrate" ]] || [[  "$input" = "bitrate" ]] || [[  "$input" = "b" ]]
then
	echo "Please entire new bitrate."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	line_to_change=$(grep "^BITRATE" config.conf)
	sed -i "s/BITRATE=$BITRATE/BITRATE=$input2/" config.conf
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Height" ]] || [[  "$input" = "height" ]] || [[  "$input" = "h" ]]
then
	echo "Please entire new height."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	line_to_change=$(grep "^HEIGHT" config.conf)
	sed -i "s/HEIGHT=$HEIGHT/HEIGHT=$input2/" config.conf
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Width" ]] || [[  "$input" = "width" ]] || [[  "$input" = "w" ]]
then
	echo "Please entire new width."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	line_to_change=$(grep "^WIDTH" config.conf)
	sed -i "s/WIDTH=$WIDTH/WIDTH=$input2/" config.conf
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Framerate" ]] || [[  "$input" = "framerate" ]] || [[  "$input" = "f" ]]
then
	echo "Please entire new framerate."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	line_to_change=$(grep "^FRAMERATE" config.conf)
	sed -i "s/FRAMERATE=$FRAMERATE/FRAMERATE=$input2/" config.conf
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

	echo "End of Program"
