#!bin/bash

echo "Please enter the setting you want to change, or 'help' for a list of changable settings"
read input
while [ "$input" = "help" ]
do
	echo "Changable settings are as follows:"
	echo "Bitrate"
	echo "Framerate"
	echo "Height"
	echo "Width"
	echo ""
	echo "Please enter the setting you want to change, or 'help' for a list of changable settings"
	read input
done

if [[ "$input" = "Bitrate" ]] || [[  "$input" = "bitrate" ]] || [[  "$input" = "b" ]]
then
	echo "Please entire new bitrate."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	sudo sed -i "0,/BITRATE/s/BITRATE.*/BITRATE=${input2}/" start_stream
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Height" ]] || [[  "$input" = "height" ]] || [[  "$input" = "h" ]]
then
	echo "Please entire new height."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	sudo sed -i "0,/HEIGHT/s/HEIGHT.*/HEIGHT=${input2}/" start_stream
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Width" ]] || [[  "$input" = "width" ]] || [[  "$input" = "w" ]]
then
	echo "Please entire new width."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	sudo sed -i "0,/WIDTH/s/WIDTH.*/WIDTH=${input2}/" start_stream
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

if [[ "$input" = "Framerate" ]] || [[  "$input" = "framerate" ]] || [[  "$input" = "f" ]]
then
	echo "Please entire new framerate."
	read input2
	sudo systemctl stop BOREALIS_CAM.service
	sudo sed -i "0,/FRAMERATE/s/FRAMERATE.*/FRAMERATE=${input2}/" start_stream
	sudo systemctl start BOREALIS_CAM.service
	echo "Changes made successfully, stream has been restarted with updated settings"
fi

	echo "End of Program"
