#!/bin/bash
WIDTH=1550
# Maximum is 1550!
HEIGHT=1152
# Maximum is 1152!
BITRATE=1200000
#BITRATE  <-- when being edited, only the first instance of BITRATE should change, hence the one in this comment should NOT change
FRAMERATE=30

#/usr/local/bin/libcamera-vid --width $WIDTH --height $HEIGHT -g 15 -b $BITRATE

#/usr/local/bin/libcamera-vid --width 1280 --height 720 -g 15 -b 12000000 --vflip -t 0 --framerate 30 -n -o - |/home/pi/BOREALIS_Cam/test-launch "fdsrc fd=0 ! h264parse ! rtph264pay name=pay0 pt=96"
#/usr/local/bin/libcamera-vid --width 1280 --height 720 -g 15 -b 1200000 --vflip -t 0 --framerate 30 -n -o - | /usr/bin/ffmpeg -r 30 -f h264 -i - -fflags +genpts -an -vcodec copy -metadata service_name="2024 Eclipse HAB 1" -metadata service_provider=UMHAB -r 30 -f rtp_mpegts rtp://224.3.0.64:8554?localaddr=192.168.1.3\&ttl=2/ -vcodec copy -f mpegts /home/pi/`date '+%Y%m%d-%H%m%S.%N'`.mpegts
#this one worked okay, maybe had problems with disconections
/usr/bin/libcamera-vid --width $WIDTH --height $HEIGHT -g 15 -b $BITRATE --vflip -t 0 --framerate $FRAMERATE -n -o - | /usr/bin/ffmpeg -r $FRAMERATE -f h264 -i - -fflags +genpts -an -vcodec copy -metadata service_name="2024 Eclipse HAB 1" -metadata service_provider=UMHAB -r $FRAMERATE -f rtp_mpegts rtp://192.168.1.49:8554?localaddr=192.168.1.49\&ttl=2/ -vcodec copy -f mpegts /home/pi/Desktop/Videos`date '+%Y%m%d-%H%m%S.%N'`.mpegts
