#!/bin/bash
WIDTH=1550
# Maximum is 1550!
HEIGHT=1152
# Maximum is 1152!
BITRATE=1200000
#BITRATE  <-- when being edited, only the first instance of BITRATE should change, hence the one in this comment should NOT change
FRAMERATE=30

IP="XX.XX.XX.XX"

/usr/bin/libcamera-vid --width $WIDTH --height $HEIGHT -g 15 -b $BITRATE --vflip -t 0 --framerate $FRAMERATE -n -o - | /usr/bin/ffmpeg -r $FRAMERATE -f h264 -i - -fflags +genpts -an -vcodec copy -metadata service_name="2024 Eclipse HAB 1" -metadata service_provider=UMHAB -r $FRAMERATE -f rtp_mpegts rtp://$IP:8554?localaddr=$IP\&ttl=2/ -vcodec copy -f mpegts /home/$USER/Desktop/Videos`date '+%Y%m%d-%H%m%S.%N'`.mpegts
